services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - DATABASE_URL=postgresql://fundraiser:${POSTGRES_PASSWORD:-fundraiser}@db:5432/fundraiser
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fundraiser
      - POSTGRES_USER=fundraiser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-fundraiser}
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 